# 应用服务 WEB 访问端口
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  ssl:
    enabled: false
  servlet:
    context-path: /ews

# 数据库连接配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://112.124.106.58:3306/fastdev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: HUST321
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis 连接集群
  redis:
    sentinel:
      master: mymaster
      nodes:
        - 192.168.1.138:26379
        - 192.168.1.138:26380
        - 192.168.1.138:26381
    password: Hust@411

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Python 脚本位置
algorithm:
  pythonFilePath: /home

logging:
  level:
    com.hust.encrypt: info

# Redis 单节点配置（如果需要，可以解开注释）
# redis:
#   host: 127.0.0.1
#   port: 6379
#   password:
#   timeout: 2000
